services:
  db:
    image: postgres:16-alpine
    container_name: amigo-secreto-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=amigo_secreto
      - POSTGRES_USER=gabriel
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
